name: PyDoc GitHub Pages Deploy Action
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
          contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install requirements for documentation generation
      run: |
        python -m pip install --upgrade pip setuptools wheel build
        python -m pip install pdoc3
        sudo make install
        cd python
        python -m build
        python -m pip install -e .

    - name: Generate API documentation with pydoc (pdoc3)
      run: |

        python -m pdoc --html sista --output-dir docs --force

    - name: Push API documentation to GitHub Pages (if on main branch)
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/sista
        commit_message: "Generate API documentation"
        destination_dir: sista-python
