# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: Install the sista library
        run: |
          sudo PREFIX=/usr/local make install

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Build release distributions
        run: |
          # NOTE: put your own distribution build steps here.
          cd python
          python -m pip install build
          python -m build
    
      - name: Install cibuildwheel
        run: |
          cd python
          python -m pip install cibuildwheel

      - name: Build wheels
        # https://cibuildwheel.pypa.io/en/stable/configuration/#environment-variables
        run: |
          cd python
          cibuildwheel --output-dir wheelhouse

      - name: Upload wheels (linux)
        uses: actions/upload-artifact@v4
        with:
          name: release-wheels-linux
          path: python/wheelhouse/

  release-build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: Install the sista library
        run: |
          make install

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        # https://cibuildwheel.pypa.io/en/stable/configuration/#environment-variables
        run: |
          cd python
          cibuildwheel --output-dir wheelhouse

      - name: Upload wheels (windows)
        uses: actions/upload-artifact@v4
        with:
          name: release-wheels-windows
          path: python/wheelhouse/

  release-build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install the sista library
        run: |
          sudo PREFIX=/usr/local make install

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        run: |
          cd python
          cibuildwheel --output-dir wheelhouse

      - name: Upload wheels (macos)
        uses: actions/upload-artifact@v4
        with:
          name: release-wheels-macos
          path: python/wheelhouse/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
      - release-build-windows
      - release-build-macos
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/sista

    steps:
      - name: Retrieve wheels (linux)
        uses: actions/download-artifact@v4
        with:
          name: release-wheels-linux
          path: python/wheelhouse/

      - name: Retrieve wheels (windows)
        uses: actions/download-artifact@v4
        with:
          name: release-wheels-windows
          path: python/wheelhouse/

      - name: Retrieve wheels (macos)
        uses: actions/download-artifact@v4
        with:
          name: release-wheels-macos
          path: python/wheelhouse/

      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/wheelhouse/
