# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create local install prefix
        run: mkdir -p python/_install

      - name: Install the sista library into local prefix
        run: |
          make install PREFIX=${{ github.workspace }}/python/_install

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Build release distributions
        run: |
          cd python
          python -m pip install build
          python -m build

      - name: Install cibuildwheel
        run: |
          cd python
          python -m pip install cibuildwheel

      - name: Build wheels
        env:
          PREFIX: ${{ github.workspace }}/python/_install
          CPPFLAGS: -I${{ github.workspace }}/python/_install/include
          CFLAGS: -I${{ github.workspace }}/python/_install/include
          LDFLAGS: -L${{ github.workspace }}/python/_install/lib -Wl,-rpath,${{ github.workspace }}/python/_install/lib
          PKG_CONFIG_PATH: ${{ github.workspace }}/python/_install/lib/pkgconfig
          LD_LIBRARY_PATH: ${{ github.workspace }}/python/_install/lib
        run: |
          cd python
          cibuildwheel --output-dir wheelhouse

      - name: Upload wheels (linux)
        uses: actions/upload-artifact@v4
        with:
          name: release-wheels-linux
          path: python/wheelhouse/

  release-build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create local install prefix
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "$env:GITHUB_WORKSPACE\python\_install"

      - name: Install the sista library into local prefix
        run: |
          make install PREFIX=${{ github.workspace }}\\python\\_install

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        env:
          PREFIX: ${{ github.workspace }}\\python\\_install
          INCLUDE: ${{ github.workspace }}\\python\\_install\\include
          LIB: ${{ github.workspace }}\\python\\_install\\lib
        run: |
          cd python
          cibuildwheel --output-dir wheelhouse

      - name: Upload wheels (windows)
        uses: actions/upload-artifact@v4
        with:
          name: release-wheels-windows
          path: python/wheelhouse/

  release-build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create local install prefix
        run: mkdir -p python/_install

      - name: Install the sista library into local prefix
        run: |
          make install PREFIX=${{ github.workspace }}/python/_install

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        env:
          PREFIX: ${{ github.workspace }}/python/_install
          CPPFLAGS: -I${{ github.workspace }}/python/_install/include
          CFLAGS: -I${{ github.workspace }}/python/_install/include
          LDFLAGS: -L${{ github.workspace }}/python/_install/lib -Wl,-rpath,${{ github.workspace }}/python/_install/lib
          PKG_CONFIG_PATH: ${{ github.workspace }}/python/_install/lib/pkgconfig
          DYLD_LIBRARY_PATH: ${{ github.workspace }}/python/_install/lib
        run: |
          cd python
          cibuildwheel --output-dir wheelhouse

      - name: Upload wheels (macos)
        uses: actions/upload-artifact@v4
        with:
          name: release-wheels-macos
          path: python/wheelhouse/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
      - release-build-windows
      - release-build-macos
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/sista

    steps:
      - name: Retrieve wheels (linux)
        uses: actions/download-artifact@v4
        with:
          name: release-wheels-linux
          path: python/wheelhouse/

      - name: Retrieve wheels (windows)
        uses: actions/download-artifact@v4
        with:
          name: release-wheels-windows
          path: python/wheelhouse/

      - name: Retrieve wheels (macos)
        uses: actions/download-artifact@v4
        with:
          name: release-wheels-macos
          path: python/wheelhouse/

      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/wheelhouse/
